In [ ]:
! pip install transformers


In [4]:
#Sentiment Classification
from transformers import pipeline
classifier = pipeline("sentiment-analysis")
output = classifier("The new movie is fantastic - I really liked it")
print(output)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


e:\VScode-py\nlpenv\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Violet\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


[{'label': 'POSITIVE', 'score': 0.999884843826294}]


In [5]:
classifier = pipeline("sentiment-analysis")
sentences = ["Tennis is my favorite sport",
           "I do not like football much though"]
output = classifier(sentences)
for items in output:
  print(items)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'label': 'POSITIVE', 'score': 0.9995262622833252}
{'label': 'NEGATIVE', 'score': 0.9992341995239258}


In [6]:
#Passing Model from Hugging Face Hub to a Pipelines

classifier = pipeline("sentiment-analysis", model = "finiteautomata/bertweet-base-sentiment-analysis")
sentences = ["The movie is fantastic",
           "I did not like the ice cream today",
           "I am visiting Paris today"]
output = classifier(sentences)
print(output)

emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0


[{'label': 'POS', 'score': 0.9924730062484741}, {'label': 'NEG', 'score': 0.9755329489707947}, {'label': 'NEU', 'score': 0.8113422393798828}]


In [8]:
#three main tasks performed by the pipeline() function:Tokenization,Generating Model Outputs,Post-processing Model output


#Tokenization
from transformers import AutoTokenizer
model_name = "finiteautomata/bertweet-base-sentiment-analysis"
tokenizer = AutoTokenizer.from_pretrained(model_name)

sentences = ["The movie is fantastic",
           "I did not like the ice cream today",
           "I am visiting Paris today"]

inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors = "pt")
print(inputs)


emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0


{'input_ids': tensor([[   0,   47,  566,   17, 2877,    2,    1,    1,    1,    1],
        [   0,    8,  103,   46,   43,    6, 1110, 2074,  128,    2],
        [   0,    8,  155, 6512, 3177,  128,    2,    1,    1,    1]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}


In [9]:
#Generating Model Outputs

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(model_name)
outputs = model(**inputs)
print(outputs.logits)

tensor([[-2.1325, -1.4309,  3.8535],
        [ 3.0700, -0.7706, -2.5563],
        [-3.3058,  2.5170,  1.0454]], grad_fn=<AddmmBackward0>)


In [10]:
#Post-processing Model output
import torch

predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)


tensor([[0.0025, 0.0050, 0.9925],
        [0.9755, 0.0210, 0.0035],
        [0.0024, 0.8113, 0.1863]], grad_fn=<SoftmaxBackward0>)


In [11]:
#final predictions

print(torch.argmax(predictions, dim=1))
print(model.config.id2label)

tensor([2, 0, 1])
{0: 'NEG', 1: 'NEU', 2: 'POS'}
